export const tweets = [
  {
    id: 0,
    profilePicture: "assets/images/user-profil.png",
    name: "Sami3160",
    username: "@sami3160",
    date: "1h",
    text: "Hehe, @HarshBaka and @YashSenpai and me taking selfie <3",
    image: "assets/images/tw-pic-2.png",
    link:"https://github.com/Sami3160",
  },
  {
    id: 1,
    profilePicture: "assets/images/tw-yash.png",
    name: "Yash boiii ⚔",
    username: "@YashSenpai69",
    date: "2h",
    text: "Yoo, look at this cool meme i found on internet😂#codingwithfun #coding #meme #codingmeme",
    image: "assets/images/tw-pic-1.png",
    link:"https://github.com/Yash-Ainapure",
  },
  {
    id: 2,
    profilePicture: "assets/images/tw-harsh.png",
    name: "Harsh Oni-chan💦",
    username: "@HarshBaka",
    date: "4d",
    text: "you and meeee, ayee ayee ayeee-eee-eeee #bucketlist #YouAndMe #YouAndMeLyrics #soulmate #waifu #bakawaifu #UwU",
    image: "assets/images/UnMe.png",
    link:"https://github.com/Harsh2504",
  },
];
